package Entidad;
// Generated Feb 16, 2016 9:23:31 PM by Hibernate Tools 4.3.1



/**
 * EegSignals generated by hbm2java
 */
public class EegSignals  implements java.io.Serializable {


     private int idEegSignals;
     private String nombrePersona;
     private int delta;
     private int theta;
     private int lowAlpha;
     private int highAlpha;
     private int lowBeta;
     private int highBeta;
     private int lowGamma;
     private int highGamma;
     private String lado;

    public EegSignals() {
    }

    public EegSignals(int idEegSignals, String nombrePersona, int delta, int theta, int lowAlpha, int highAlpha, int lowBeta, int highBeta, int lowGamma, int highGamma, String lado) {
       this.idEegSignals = idEegSignals;
       this.nombrePersona = nombrePersona;
       this.delta = delta;
       this.theta = theta;
       this.lowAlpha = lowAlpha;
       this.highAlpha = highAlpha;
       this.lowBeta = lowBeta;
       this.highBeta = highBeta;
       this.lowGamma = lowGamma;
       this.highGamma = highGamma;
       this.lado = lado;
    }
   
    public int getIdEegSignals() {
        return this.idEegSignals;
    }
    
    public void setIdEegSignals(int idEegSignals) {
        this.idEegSignals = idEegSignals;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public int getDelta() {
        return this.delta;
    }
    
    public void setDelta(int delta) {
        this.delta = delta;
    }
    public int getTheta() {
        return this.theta;
    }
    
    public void setTheta(int theta) {
        this.theta = theta;
    }
    public int getLowAlpha() {
        return this.lowAlpha;
    }
    
    public void setLowAlpha(int lowAlpha) {
        this.lowAlpha = lowAlpha;
    }
    public int getHighAlpha() {
        return this.highAlpha;
    }
    
    public void setHighAlpha(int highAlpha) {
        this.highAlpha = highAlpha;
    }
    public int getLowBeta() {
        return this.lowBeta;
    }
    
    public void setLowBeta(int lowBeta) {
        this.lowBeta = lowBeta;
    }
    public int getHighBeta() {
        return this.highBeta;
    }
    
    public void setHighBeta(int highBeta) {
        this.highBeta = highBeta;
    }
    public int getLowGamma() {
        return this.lowGamma;
    }
    
    public void setLowGamma(int lowGamma) {
        this.lowGamma = lowGamma;
    }
    public int getHighGamma() {
        return this.highGamma;
    }
    
    public void setHighGamma(int highGamma) {
        this.highGamma = highGamma;
    }
    public String getLado() {
        return this.lado;
    }
    
    public void setLado(String lado) {
        this.lado = lado;
    }




}


