/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.EegControl;
import Entidad.EegSignals;
import java.awt.List;
import java.awt.TrayIcon;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Conexion.ClienteTCP;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author LiutsCertificatedProfessional Utilizando el parte del codigo de
 * ericblue
 */
public class InterfazDiadema extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Interfaz_Diadema
     */
    private ClienteTCP clienteTCP;
    private String personaAEvaluar;

    public InterfazDiadema() {
        personaAEvaluar = JOptionPane.showInputDialog("Escriba su nombre");
        initComponents();
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        principalPn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ladoLbl = new javax.swing.JLabel();
        concentracionLbl = new javax.swing.JLabel();
        relajacionLbl = new javax.swing.JLabel();
        contadorLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lowBetaLbl = new javax.swing.JLabel();
        deltaLbl = new javax.swing.JLabel();
        highBetaLbl = new javax.swing.JLabel();
        lowGammaLbl = new javax.swing.JLabel();
        highGammaLbl = new javax.swing.JLabel();
        thetaLbl = new javax.swing.JLabel();
        lowAlphaLbl = new javax.swing.JLabel();
        highAlphaLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos Enviados por la MindWave: ");

        ladoLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ladoLbl.setText("Piensa en el lado:");

        concentracionLbl.setText("Concentracion: ");

        relajacionLbl.setText("Relajacion:");

        contadorLbl.setText("Contador:");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalPnLayout = new javax.swing.GroupLayout(principalPn);
        principalPn.setLayout(principalPnLayout);
        principalPnLayout.setHorizontalGroup(
            principalPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contadorLbl)
                .addGap(77, 77, 77))
            .addGroup(principalPnLayout.createSequentialGroup()
                .addGroup(principalPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPnLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ladoLbl))
                    .addGroup(principalPnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(principalPnLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(principalPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relajacionLbl)
                            .addComponent(concentracionLbl)))
                    .addGroup(principalPnLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jButton1)))
                .addContainerGap(610, Short.MAX_VALUE))
        );
        principalPnLayout.setVerticalGroup(
            principalPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(contadorLbl)
                .addGap(5, 5, 5)
                .addComponent(ladoLbl)
                .addGap(218, 218, 218)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(concentracionLbl)
                .addGap(48, 48, 48)
                .addComponent(relajacionLbl)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("General", principalPn);

        lowBetaLbl.setText("Low Beta:");

        deltaLbl.setText("Delta: ");

        highBetaLbl.setText("High Beta:");

        lowGammaLbl.setText("Low Gamma:");

        highGammaLbl.setText("High Gamma:");

        thetaLbl.setText("Theta:");

        lowAlphaLbl.setText("LowAlpha:");

        highAlphaLbl.setText("High Alpha: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highBetaLbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowBetaLbl)
                            .addComponent(highGammaLbl)
                            .addComponent(lowGammaLbl))
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowAlphaLbl)
                            .addComponent(highAlphaLbl)
                            .addComponent(thetaLbl)
                            .addComponent(deltaLbl))))
                .addContainerGap(733, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowBetaLbl)
                    .addComponent(deltaLbl))
                .addGap(30, 30, 30)
                .addComponent(highBetaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thetaLbl)
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowGammaLbl)
                    .addComponent(lowAlphaLbl))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highGammaLbl)
                    .addComponent(highAlphaLbl))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazDiadema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazDiadema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazDiadema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDiadema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazDiadema interfaz = new InterfazDiadema();
                boolean condicion = false;
                while (!condicion) {
                    condicion = interfaz.crearConexion();
                }
                interfaz.setVisible(true);
                if (condicion) {
                    (new Thread(interfaz)).start();
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel concentracionLbl;
    private javax.swing.JLabel contadorLbl;
    private javax.swing.JLabel deltaLbl;
    private javax.swing.JLabel highAlphaLbl;
    private javax.swing.JLabel highBetaLbl;
    private javax.swing.JLabel highGammaLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel ladoLbl;
    private javax.swing.JLabel lowAlphaLbl;
    private javax.swing.JLabel lowBetaLbl;
    private javax.swing.JLabel lowGammaLbl;
    private javax.swing.JPanel principalPn;
    private javax.swing.JLabel relajacionLbl;
    private javax.swing.JLabel thetaLbl;
    // End of variables declaration//GEN-END:variables

    public boolean crearConexion() {
        clienteTCP = new ClienteTCP();
        clienteTCP.connect();
        if (clienteTCP.isConnected() == true) {
            return true;
        } else {
            return false;
        }
    }

    public void recibirDatos() throws InterruptedException {
        ArrayList<EegSignals> listaEeg = new ArrayList<EegSignals>();
        EegControl eegControl = new EegControl();
        JLabel puntoLbl = new JLabel(".");
        puntoLbl.setLocation(540, 315);
        puntoLbl.setFont(new Font("Serif", Font.PLAIN, 100));
        puntoLbl.setSize(400,203);
        puntoLbl.setVisible(true);
        principalPn.add(puntoLbl);
        int contador = 0;
        int contadorFinal = 0;

        String lado = "derecho";
        for (int k = 5; k > 0; k--) {
            if (k > 4) {
                puntoLbl.setText("Espera!!!!");
            } else {
                puntoLbl.setText(".");
            }
            ladoLbl.setText("Piensa en mover el punto al lado: "
                    + lado + " en " + k);
            Thread.sleep(1000);
        }
        try {
            while (clienteTCP.isDataAvailable()) {

                ladoLbl.setText("Piensa en mover el punto al lado: " + lado + " Ya:");
                EegSignals eeg = new EegSignals();
                String clientData = clienteTCP.getData();
                JSONObject json = new JSONObject(clientData);
                if (!json.isNull("eegPower")) {

                    JSONObject eegPower = json.getJSONObject("eegPower");

                    deltaLbl.setText("Delta: " + Integer.toString(eegPower.getInt("delta")));
                    thetaLbl.setText("Theta: " + Integer.toString(eegPower.getInt("theta")));
                    lowAlphaLbl.setText("LowAlpha: " + Integer.toString(eegPower.getInt("lowAlpha")));
                    highAlphaLbl.setText("High Alpha: " + Integer.toString(eegPower.getInt("highAlpha")));
                    lowBetaLbl.setText("Low Beta: " + Integer.toString(eegPower.getInt("lowBeta")));
                    highBetaLbl.setText("High Beta: " + Integer.toString(eegPower.getInt("highBeta")));
                    lowGammaLbl.setText("Low Gamma: " + Integer.toString(eegPower.getInt("lowGamma")));
                    highGammaLbl.setText("High Gamma: " + Integer.toString(eegPower.getInt("highGamma")));

                    eeg.setNombrePersona(personaAEvaluar);
                    eeg.setDelta(eegPower.getInt("delta"));
                    eeg.setTheta(eegPower.getInt("theta"));
                    eeg.setLowAlpha(eegPower.getInt("lowAlpha"));
                    eeg.setHighAlpha(eegPower.getInt("highAlpha"));
                    eeg.setLowBeta(eegPower.getInt("lowBeta"));
                    eeg.setHighBeta(eegPower.getInt("highBeta"));
                    eeg.setLowGamma(eegPower.getInt("lowGamma"));
                    eeg.setHighGamma(eegPower.getInt("highGamma"));
                    eeg.setLado(lado);
                    if (!json.isNull("eSense")) {
                        JSONObject esense = json.getJSONObject("eSense");
                        concentracionLbl.setText("Concentracion: " + Integer.toString(esense.getInt("attention")));
                        relajacionLbl.setText("Meditacion: " + Integer.toString(esense.getInt("meditation")));
                        if (esense.getInt("attention") >= 30) {
                            listaEeg.add(eeg);
                            contador++;
                            Thread.sleep(500);
                        }
                        if (esense.getInt("attention") >= 60 && lado.equals("derecho")) {
                            puntoLbl.setLocation(puntoLbl.getLocation().x + 10, puntoLbl.getY());
                            this.repaint();
                            
                            
                        } else if (esense.getInt("attention") >= 60 && lado.equals("izquierdo")) {
                            puntoLbl.setLocation(puntoLbl.getLocation().x - 10, puntoLbl.getY());
                            this.repaint();
                        }
                    } else {
                        ladoLbl.setText("Espera unos minutos :)");
                    }
                    if (contador == 20) {
                        eegControl.Registrar(listaEeg);
                        contador = 0;
                        contadorFinal++;
                        contadorLbl.setText(contadorFinal + "");
                        listaEeg = null;
                        listaEeg = new ArrayList<EegSignals>();
                        if (lado.equals("derecho")) {
                            lado = "izquierdo";
                        } else {
                            lado = "derecho";
                        }
                        if (contadorFinal < 10) {
                            for (int k = 7; k > 0; k--) {
                                if (k > 4) {
                                    puntoLbl.setText("Espera!!!!");
                                } else {
                                    puntoLbl.setText(".");
                                }
                                ladoLbl.setText("Piensa en mover el punto al lado: "
                                        + lado + " en " + k);
                                Thread.sleep(1000);
                            }
                        }
                    }
                    if (contadorFinal == 10) {
                        JOptionPane.showMessageDialog(this, "Gracias por tu ayuda, contigo haremos un futuro mejor");
                        this.dispose();
                        System.exit(0);
                    }
                } else {
                    ladoLbl.setText("Espera unos minutos :)");
                }
            }
        } catch (JSONException e1) {
            System.out.println(e1);
        }
    }

    public void run() {
        try {
            recibirDatos();
        } catch (InterruptedException ex) {
            Logger.getLogger(InterfazDiadema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
